<?php

use Illuminate\Database\Seeder;

class PropertiesTableSeeder extends Seeder
{
    public function run()
    {
        // DB::table('properties')->truncate();

        $properties = [
            [
                'name' => 'Alqueva',
                'district' => '',
                'township' => '',
                'parish' => '',
                'type' => 'house',
                'state' => 'business',
                'business' => '',
                'cost' => 370000,
                'address' => 'xxx',
                'area' => 300,
                'territory' => 600,
                'beach' => true,
                'room' => 15,
                'bedroom' => 6,
                'wc' => 4,
                'garage' => 2,
                'pool' => 1,
                'description' => 'Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia comagni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Qui in ea voluptate velit esse quam nihil molestiae consequatur, dolorem eum fugiat quo voluptas nulla pariatur.',
                'images' => '["properties\\\\September2019\\\\house1.png","properties\\\\September2019\\\\temhouse1.png","properties\\\\September2019\\\\temhouse2.png","properties\\\\September2019\\\\temhouse3.png","properties\\\\September2019\\\\temhouse4.png"]',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name' => 'Porto-Covo',
                'district' => '',
                'township' => '',
                'parish' => '',
                'type' => 'house',
                'state' => 'business',
                'business' => '',
                'cost' => 445000,
                'address' => 'xxx',
                'territory' => 600,
                'beach' => true,
                'room' => 10,
                'area' => 300,
                'bedroom' => 4,
                'wc' => 2,
                'garage' => null,
                'pool' => 1,
                'description' => 'Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia comagni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Qui in ea voluptate velit esse quam nihil molestiae consequatur, dolorem eum fugiat quo voluptas nulla pariatur.',
                'images' => '["properties\\\\September2019\\\\house2.png","properties\\\\September2019\\\\temhouse1.png","properties\\\\September2019\\\\temhouse2.png","properties\\\\September2019\\\\temhouse3.png","properties\\\\September2019\\\\temhouse4.png"]',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name' => 'Chiado',
                'district' => '',
                'township' => '',
                'parish' => '',
                'type' => 'house',
                'state' => 'business',
                'business' => '',
                'cost' => 270000,
                'address' => 'xxx',
                'area' => '260',
                'territory' => 520,
                'beach' => false,
                'room' => 9,
                'bedroom' => 3,
                'wc' => 4,
                'garage' => null,
                'pool' => null,
                'description' => 'Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia comagni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Qui in ea voluptate velit esse quam nihil molestiae consequatur, dolorem eum fugiat quo voluptas nulla pariatur.',
                'images' => '["properties\\\\September2019\\\\house3.png","properties\\\\September2019\\\\temhouse1.png","properties\\\\September2019\\\\temhouse2.png","properties\\\\September2019\\\\temhouse3.png","properties\\\\September2019\\\\temhouse4.png"]',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name' => 'Porto - Foz',
                'district' => '',
                'township' => '',
                'parish' => '',
                'type' => 'house',
                'state' => 'business',
                'business' => '',
                'cost' => 270000,
                'address' => 'xxx',
                'area' => 260,
                'territory' => 520,
                'beach' => false,
                'room' => 9,
                'bedroom' => 5,
                'wc' => 1,
                'garage' => null,
                'pool' => null,
                'description' => 'Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia comagni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Qui in ea voluptate velit esse quam nihil molestiae consequatur, dolorem eum fugiat quo voluptas nulla pariatur.',
                'images' => '["properties\\\\September2019\\\\house4.png","properties\\\\September2019\\\\temhouse1.png","properties\\\\September2019\\\\temhouse2.png","properties\\\\September2019\\\\temhouse3.png","properties\\\\September2019\\\\temhouse4.png"]',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name' => 'Alfama',
                'district' => '',
                'township' => '',
                'parish' => '',
                'type' => 'house',
                'state' => 'business',
                'business' => '',
                'cost' => 550000,
                'address' => 'xxx',
                'area' => 360,
                'territory' => 720,
                'beach' => false,
                'room' => 10,
                'bedroom' => 5,
                'wc' => 3,
                'garage' => null,
                'pool' => null,
                'description' => 'Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia comagni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Qui in ea voluptate velit esse quam nihil molestiae consequatur, dolorem eum fugiat quo voluptas nulla pariatur.',
                'images' => '["properties\\\\September2019\\\\house5.png","properties\\\\September2019\\\\temhouse1.png","properties\\\\September2019\\\\temhouse2.png","properties\\\\September2019\\\\temhouse3.png","properties\\\\September2019\\\\temhouse4.png"]',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name' => 'Quinta do Lago',
                'district' => '',
                'township' => '',
                'parish' => '',
                'type' => 'apartment',
                'state' => 'business',
                'business' => '',
                'cost' => 445000,
                'address' => 'xxx',
                'area' => 280,
                'territory' => 560,
                'beach' => false,
                'room' => 11,
                'bedroom' => 4,
                'wc' => 4,
                'garage' => null,
                'pool' => null,
                'description' => 'Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia comagni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Qui in ea voluptate velit esse quam nihil molestiae consequatur, dolorem eum fugiat quo voluptas nulla pariatur.',
                'images' => '["properties\\\\September2019\\\\house6.png","properties\\\\September2019\\\\temhouse1.png","properties\\\\September2019\\\\temhouse2.png","properties\\\\September2019\\\\temhouse3.png","properties\\\\September2019\\\\temhouse4.png"]',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name' => 'Alqueva1',
                'district' => '',
                'township' => '',
                'parish' => '',
                'type' => 'house',
                'state' => 'business',
                'business' => '',
                'cost' => 225000,
                'address' => 'xxx',
                'area' => 300,
                'territory' => 600,
                'beach' => false,
                'room' => 14,
                'bedroom' => 6,
                'wc' => 4,
                'garage' => 2,
                'pool' => null,
                'description' => 'Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia comagni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Qui in ea voluptate velit esse quam nihil molestiae consequatur, dolorem eum fugiat quo voluptas nulla pariatur.',
                'images' => '["properties\\\\September2019\\\\house7.png","properties\\\\September2019\\\\temhouse1.png","properties\\\\September2019\\\\temhouse2.png","properties\\\\September2019\\\\temhouse3.png","properties\\\\September2019\\\\temhouse4.png"]',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name' => 'Porto-Covo1',
                'district' => '',
                'township' => '',
                'parish' => '',
                'type' => 'house',
                'state' => 'business',
                'business' => '',
                'cost' => 370000,
                'address' => 'xxx',
                'area' => 260,
                'territory' => 520,
                'beach' => false,
                'room' => 13,
                'bedroom' => 3,
                'wc' => 3,
                'garage' => null,
                'pool' => 3,
                'description' => 'Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia comagni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Qui in ea voluptate velit esse quam nihil molestiae consequatur, dolorem eum fugiat quo voluptas nulla pariatur.',
                'images' => '["properties\\\\September2019\\\\house8.png","properties\\\\September2019\\\\temhouse1.png","properties\\\\September2019\\\\temhouse2.png","properties\\\\September2019\\\\temhouse3.png","properties\\\\September2019\\\\temhouse4.png"]',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name' => 'Chiado1',
                'district' => '',
                'township' => '',
                'parish' => '',
                'type' => 'house',
                'state' => 'business',
                'business' => '',
                'cost' => 370000,
                'address' => 'xxx',
                'area' => 260,
                'territory' => 520,
                'beach' => false,
                'room' => 7,
                'bedroom' => 4,
                'wc' => 1,
                'garage' => null,
                'pool' => null,
                'description' => 'Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia comagni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Qui in ea voluptate velit esse quam nihil molestiae consequatur, dolorem eum fugiat quo voluptas nulla pariatur.',
                'images' => '["properties\\\\September2019\\\\house9.png","properties\\\\September2019\\\\temhouse1.png","properties\\\\September2019\\\\temhouse2.png","properties\\\\September2019\\\\temhouse3.png","properties\\\\September2019\\\\temhouse4.png"]',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name' => 'Porto-Covo',
                'district' => '',
                'township' => '',
                'parish' => '',
                'type' => 'house',
                'state' => 'business',
                'business' => '',
                'cost' => 445000,
                'address' => 'xxx',
                'territory' => 600,
                'beach' => true,
                'room' => 10,
                'area' => 300,
                'bedroom' => 4,
                'wc' => 2,
                'garage' => null,
                'pool' => 1,
                'description' => 'Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia comagni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Qui in ea voluptate velit esse quam nihil molestiae consequatur, dolorem eum fugiat quo voluptas nulla pariatur.',
                'images' => '["properties\\\\September2019\\\\house1.png","properties\\\\September2019\\\\temhouse1.png","properties\\\\September2019\\\\temhouse2.png","properties\\\\September2019\\\\temhouse3.png","properties\\\\September2019\\\\temhouse4.png"]',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name' => 'Chiado',
                'district' => '',
                'township' => '',
                'parish' => '',
                'type' => 'apartment',
                'state' => 'business',
                'business' => '',
                'cost' => 270000,
                'address' => 'xxx',
                'area' => '260',
                'territory' => 520,
                'beach' => false,
                'room' => 9,
                'bedroom' => 3,
                'wc' => 4,
                'garage' => null,
                'pool' => null,
                'description' => 'Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia comagni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Qui in ea voluptate velit esse quam nihil molestiae consequatur, dolorem eum fugiat quo voluptas nulla pariatur.',
                'images' => '["properties\\\\September2019\\\\house2.png","properties\\\\September2019\\\\temhouse1.png","properties\\\\September2019\\\\temhouse2.png","properties\\\\September2019\\\\temhouse3.png","properties\\\\September2019\\\\temhouse4.png"]',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name' => 'Porto - Foz',
                'district' => '',
                'township' => '',
                'parish' => '',
                'type' => 'apartment',
                'state' => 'business',
                'business' => '',
                'cost' => 270000,
                'address' => 'xxx',
                'area' => 260,
                'territory' => 520,
                'beach' => false,
                'room' => 9,
                'bedroom' => 5,
                'wc' => 1,
                'garage' => null,
                'pool' => null,
                'description' => 'Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia comagni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Qui in ea voluptate velit esse quam nihil molestiae consequatur, dolorem eum fugiat quo voluptas nulla pariatur.',
                'images' => '["properties\\\\September2019\\\\house3.png","properties\\\\September2019\\\\temhouse1.png","properties\\\\September2019\\\\temhouse2.png","properties\\\\September2019\\\\temhouse3.png","properties\\\\September2019\\\\temhouse4.png"]',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name' => 'Alfama',
                'district' => '',
                'township' => '',
                'parish' => '',
                'type' => 'house',
                'state' => 'business',
                'business' => '',
                'cost' => 550000,
                'address' => 'xxx',
                'area' => 360,
                'territory' => 720,
                'beach' => false,
                'room' => 10,
                'bedroom' => 5,
                'wc' => 3,
                'garage' => null,
                'pool' => null,
                'description' => 'Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia comagni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Qui in ea voluptate velit esse quam nihil molestiae consequatur, dolorem eum fugiat quo voluptas nulla pariatur.',
                'images' => '["properties\\\\September2019\\\\house4.png","properties\\\\September2019\\\\temhouse1.png","properties\\\\September2019\\\\temhouse2.png","properties\\\\September2019\\\\temhouse3.png","properties\\\\September2019\\\\temhouse4.png"]',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name' => 'Quinta do Lago',
                'district' => '',
                'township' => '',
                'parish' => '',
                'type' => 'house',
                'state' => 'business',
                'business' => '',
                'cost' => 445000,
                'address' => 'xxx',
                'area' => 280,
                'territory' => 560,
                'beach' => false,
                'room' => 11,
                'bedroom' => 4,
                'wc' => 4,
                'garage' => null,
                'pool' => null,
                'description' => 'Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia comagni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Qui in ea voluptate velit esse quam nihil molestiae consequatur, dolorem eum fugiat quo voluptas nulla pariatur.',
                'images' => '["properties\\\\September2019\\\\house5.png","properties\\\\September2019\\\\temhouse1.png","properties\\\\September2019\\\\temhouse2.png","properties\\\\September2019\\\\temhouse3.png","properties\\\\September2019\\\\temhouse4.png"]',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name' => 'Alqueva1',
                'district' => '',
                'township' => '',
                'parish' => '',
                'type' => 'house',
                'state' => 'business',
                'business' => '',
                'cost' => 225000,
                'address' => 'xxx',
                'area' => 300,
                'territory' => 600,
                'beach' => false,
                'room' => 14,
                'bedroom' => 6,
                'wc' => 4,
                'garage' => 2,
                'pool' => null,
                'description' => 'Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia comagni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Qui in ea voluptate velit esse quam nihil molestiae consequatur, dolorem eum fugiat quo voluptas nulla pariatur.',
                'images' => '["properties\\\\September2019\\\\house6.png","properties\\\\September2019\\\\temhouse1.png","properties\\\\September2019\\\\temhouse2.png","properties\\\\September2019\\\\temhouse3.png","properties\\\\September2019\\\\temhouse4.png"]',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name' => 'Porto-Covo1',
                'district' => '',
                'township' => '',
                'parish' => '',
                'type' => 'apartment',
                'state' => 'business',
                'business' => '',
                'cost' => 370000,
                'address' => 'xxx',
                'area' => 260,
                'territory' => 520,
                'beach' => false,
                'room' => 13,
                'bedroom' => 3,
                'wc' => 3,
                'garage' => null,
                'pool' => 3,
                'description' => 'Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia comagni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Qui in ea voluptate velit esse quam nihil molestiae consequatur, dolorem eum fugiat quo voluptas nulla pariatur.',
                'images' => '["properties\\\\September2019\\\\house7.png","properties\\\\September2019\\\\temhouse1.png","properties\\\\September2019\\\\temhouse2.png","properties\\\\September2019\\\\temhouse3.png","properties\\\\September2019\\\\temhouse4.png"]',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name' => 'Chiado1',
                'district' => '',
                'township' => '',
                'parish' => '',
                'type' => 'house',
                'state' => 'business',
                'business' => '',
                'cost' => 370000,
                'address' => 'xxx',
                'area' => 260,
                'territory' => 520,
                'beach' => false,
                'room' => 7,
                'bedroom' => 4,
                'wc' => 1,
                'garage' => null,
                'pool' => null,
                'description' => 'Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia comagni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Qui in ea voluptate velit esse quam nihil molestiae consequatur, dolorem eum fugiat quo voluptas nulla pariatur.',
                'images' => '["properties\\\\September2019\\\\house8.png","properties\\\\September2019\\\\temhouse1.png","properties\\\\September2019\\\\temhouse2.png","properties\\\\September2019\\\\temhouse3.png","properties\\\\September2019\\\\temhouse4.png"]',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],

        ];

        DB::table('properties')->insert($properties);
    }
}
